@baseUrl = http://localhost:5001/api

### Crear un nuevo usuario
POST {{@baseUrl}}/courses
Content-Type: application/json

{
  "active": true,
  "description": "Curso avanzado de desarrollo web con Node.js",
  "img": "https://example.com/image.jpg",
  "maxStudents": 30,
  "mentor": "64df45e71c8768a72b5f9a23",
  "modalidad": "Online",
  "plataforma": "Zoom",
  "precio": 200,
  "schedules": [
    {
      "startDate": "2024-09-01T09:00:00Z",
      "endDate": "2024-12-01T11:00:00Z",
      "days": ["Lunes", "Miércoles", "Viernes"],
      "startHour": "09:00",
      "endHour": "11:00",
      "duration": 120
    }
  ],
  "students": ["64df45e71c8768a72b5f9a24", "64df45e71c8768a72b5f9a25"],
  "tag": ["64df45e71c8768a72b5f9a26", "64df45e71c8768a72b5f9a27"],
  "title": "Desarrollo Web con Node.js"
}
###

POST http://localhost:5001/api/courses
Content-Type: application/json

{
  "active": false,
  "description": "Curso introductorio a la inteligencia artificial",
  "img": "https://example.com/ai-course.jpg",
  "maxStudents": 50,
  "mentor": "64df45e71c8768a72b5f9b12",
  "modalidad": "Presencial",
  "plataforma": "Campus Virtual",
  "precio": 150,
  "schedules": [
    {
      "startDate": "2024-10-01T08:30:00Z",
      "endDate": "2024-12-15T10:30:00Z",
      "days": ["Martes", "Jueves"],
      "startHour": "08:30",
      "endHour": "10:30",
      "duration": 120
    }
  ],
  "students": ["64df45e71c8768a72b5f9b34", "64df45e71c8768a72b5f9b35", "64df45e71c8768a72b5f9b36"],
  "tag": ["64df45e71c8768a72b5f9b45", "64df45e71c8768a72b5f9b46"],
  "title": "Introducción a la Inteligencia Artificial"
}

### Obtener todos los usuarios
GET http://localhost:5001/api/courses/

### Obtener un usuario por ID
GET http://localhost:5001/api/courses/66ccee5da9ee3cfd465f2b71

### Actualizar un usuario
PUT http://localhost:5001/api/courses/66cce94ac5e26793cb598991
Content-Type: application/json

{
  "active": true,
  "description": "Curso avanzado de desarrollo web con Node.js",
  "img": "https://example.com/image.jpg",
  "maxStudents": 30,
  "mentor": "64df45e71c8768a72b5f9a23",
  "modalidad": "Online",
  "plataforma": "Meet",
  "precio": 200,
  "schedules": [
    {
      "startDate": "2024-09-01T09:00:00Z",
      "endDate": "2024-12-01T11:00:00Z",
      "days": ["Lunes", "Miércoles", "Viernes"],
      "startHour": "09:00",
      "endHour": "11:00",
      "duration": 120
    }
  ],
  "students": ["64df45e71c8768a72b5f9a24", "64df45e71c8768a72b5f9a25"],
  "tag": ["64df45e71c8768a72b5f9a26", "64df45e71c8768a72b5f9a27"],
  "title": "Desarrollo Web con Node.js"
}

### Eliminar un usuario
DELETE http://localhost:5001/api/courses/66cce94ac5e26793cb598991
